test:
  tags:
    - cvmfs
  before_script:
    - set -o xtrace             # Print command before executing it
    - set -o errexit            # make your script exit when a command fails.
    - set -o pipefail           # exit status of the last command that threw a non-zero exit code is returned
    - shopt -s expand_aliases   # CRUCIAL for cmsrel, etc as aliases not expanded in non-interactive shells
    # check CVMFS
    - ls /cvmfs/cms.cern.ch/

